clean up

diff --git a/.github/workflows/on_release_created_or_updated.yml b/.github/workflows/on_release_created_or_updated.yml
--- a/.github/workflows/on_release_created_or_updated.yml
+++ b/.github/workflows/on_release_created_or_updated.yml
@@ -2,7 +2,6 @@ name: Release Published
 
 on:
   workflow_dispatch:
-  pull_request:
   release:
     types: [ created, edited ]
 
@@ -17,13 +16,13 @@ jobs:
         shell: bash
         run: echo "EXPECTED_RELEASE_TAG=$(./gradlew -q printVersionName)" >> "$GITHUB_ENV"
 
-#      - name: Fail if the release version and the project version do not match
-#        if: ${{ github.event.release.tag_name != env.EXPECTED_RELEASE_TAG }}
-#        run: |
-#          echo "The release tag is invalid: [${{ github.event.release.tag_name }}]"
-#          echo "The expected release tag is: [${{ env.EXPECTED_RELEASE_TAG }}]"
-#          echo "The release tag must match project version."
-#          exit 1
+      - name: Fail if the release version and the project version do not match
+        if: ${{ github.event.release.tag_name != env.EXPECTED_RELEASE_TAG }}
+        run: |
+          echo "The release tag is invalid: [${{ github.event.release.tag_name }}]"
+          echo "The expected release tag is: [${{ env.EXPECTED_RELEASE_TAG }}]"
+          echo "The release tag must match project version."
+          exit 1
 
   build_and_push_docker_image_amd64:
     name: Push to DockerHub (tag=stellar/anchor-platform:${{ github.event.release.tag_name }}) - AMD64
@@ -35,7 +34,6 @@ jobs:
         shell: bash
         run: echo "EXPECTED_RELEASE_TAG=$(./gradlew -q printVersionName)" >> "$GITHUB_ENV"
 
-      # Use a Buildx builder with the docker-container driver (required for --platform)
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
         with:
@@ -55,8 +53,7 @@ jobs:
         with:
           context: .
           file: ./Dockerfile
-          push: false
-#          push: true
+          push: true
           platforms: linux/amd64
           tags: |
             stellar/anchor-platform:${{ env.EXPECTED_RELEASE_TAG }}
@@ -77,7 +74,6 @@ jobs:
         shell: bash
         run: echo "EXPECTED_RELEASE_TAG=$(./gradlew -q printVersionName)" >> "$GITHUB_ENV"
 
-      # Use a Buildx builder with the docker-container driver (required for --platform)
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
         with:
@@ -97,12 +93,8 @@ jobs:
         with:
           context: .
           file: ./Dockerfile
-          push: false
-          #          push: true
-          # Optional but often useful to quiet SBOM/provenance warnings on multi-arch
-          provenance: false
+          push: true
           platforms: linux/arm64
-          #          platforms: linux/amd64,linux/arm64
           tags: |
             stellar/anchor-platform:${{ env.EXPECTED_RELEASE_TAG }}
             stellar/anchor-platform:latest
