Clean up

diff --git a/.github/workflows/on_release_created_or_updated.yml b/.github/workflows/on_release_created_or_updated.yml
--- a/.github/workflows/on_release_created_or_updated.yml
+++ b/.github/workflows/on_release_created_or_updated.yml
@@ -1,8 +1,6 @@
 name: Release Published
 
 on:
-  pull_request:
-    types: [opened, reopened, synchronize]
   workflow_dispatch:
   release:
     types: [ created, edited ]
@@ -20,13 +18,13 @@ jobs:
           echo "EXPECTED_RELEASE_TAG=$(${{github.workspace}}/gradlew -q printVersionName)"
           echo "EXPECTED_RELEASE_TAG=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_ENV
 
-#      - name: Fail if the release version and the project version do not match
-#        if: ${{ github.event.release.tag_name != env.EXPECTED_RELEASE_TAG }}
-#        run: |
-#          echo "The release tag is invalid: [${{ github.event.release.tag_name }}]"
-#          echo "The expected release tag is: [${{ env.EXPECTED_RELEASE_TAG }}]"
-#          echo "The release tag must match project version."
-#          exit 1
+      - name: Fail if the release version and the project version do not match
+        if: ${{ github.event.release.tag_name != env.EXPECTED_RELEASE_TAG }}
+        run: |
+          echo "The release tag is invalid: [${{ github.event.release.tag_name }}]"
+          echo "The expected release tag is: [${{ env.EXPECTED_RELEASE_TAG }}]"
+          echo "The release tag must match project version."
+          exit 1
 
       - name: Docker Login
         uses: docker/login-action@v2.1.0
